# Generated by Django 4.0.4 on 2022-04-28 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 23, 34, 56, 48471)),
        ),
    ]
