# Generated by Django 4.0.4 on 2022-04-29 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_alter_todotask_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 17, 23, 22, 725948)),
        ),
    ]
